### ISSUE TITLE
Files missing in folder ‘opencood/data_utils’

### ISSUE THREAD

**Issue by jeffreychou777** [luotianyou349/PnPDA#1]
Hi,
Thanks for your amazing work!
I  encountered a problem when I was trying to use the codebase and I have double-checked the codebase to ensure that this is indeed the case.
Some files were lost in the folder "opencood/data_utils", I not sure if these files are essential to the codebase.
eg.
/opencood/data_utils/post_processor/bev_postprocessor 
/opencood/data_utils/post_processor/ciassd_postprocessor
/opencood/data_utils/post_processor/fpvrcnn_postprocessor 
/opencood.data_utils/pre_processor/bev_preprocessor
and a Class BaseDatasetv2 lost in /opencood/datasets/basedataset.py

This problem will raise a import error in __init__.py and a inherit error in inter_mediate_dataset.py

Hope for your reply!

**Comment by luotianyou349** [comment]
Thanks for your attention and feedback, I have fixed the import error bug. At the same time, my code will not use other post-processors and pre-processors. Therefore, I removed them from "opencood/data_utils"

**Comment by jeffreychou777** [comment]
Hi, Tianyou
Thanks for your quick reply.
After I change the inheritance of the Class IntermediateFusionDataset to basedataset.BaseDataset.
A new error occurred:
![error](https://github.com/user-attachments/assets/04bfd366-7579-4807-963c-e9b1fdeda239)
The dict ''selected_cav_base" don't have correct and enough content.
![selected_cav_base](https://github.com/user-attachments/assets/3802ae43-4ac4-4b70-916b-467ec21567eb)
![line_code](https://github.com/user-attachments/assets/b613f76a-70dd-445d-a881-40e66d4bf837)

**Comment by luotianyou349** [comment]
Sorry, this error was because I used the wrong IntermediateFusionDataset, I have updated it now

**Comment by jeffreychou777** [comment]
It worked! Thanks for your help.
